---
version: 2.1

executors:
  golang:
    docker:
      - image: cimg/go:1.15
  ruby:
    docker:
      - image: ruby:2.7

jobs:
  build:
    executor: golang
    steps:
      - checkout
      - run: "cd ./src && make binaries"
  unit-test:
    executor: golang
    steps:
      - checkout
      - run: "cd ./src && go test ./..."
  test-success:
    executor: golang
    steps:
      - checkout
      - run: "make test-impl cmd-parser-text=echo"
  test-python:
    machine: true
    steps:
      - checkout
      - run: "make test_prometheus_client_python_parser"
  test-golang:
    executor: golang
    steps:
      - checkout
      - run: "make test_open_metrics_validator"
  kdrfc:
    executor: ruby
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec kdrfc specification/OpenMetrics.md
      - run: git diff --exit-code

workflows:
  version: 2
  openmetrics:
    jobs:
      - build
      - unit-test
      - kdrfc
      - test-python
      - test-golang
